# Generated by Django 4.2.16 on 2024-09-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mabar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mabarsession',
            name='player',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='MabarSession',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
