# Generated by Django 4.2.16 on 2024-09-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabar', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mabar',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='status',
            field=models.CharField(choices=[('antri', 'Dalam Antrian'), ('salah_id', 'Salah ID User'), ('kurang', 'Donasi Kurang')], default='antri', max_length=10),
        ),
    ]
