# Generated by Django 4.2.16 on 2024-09-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mabar', '0004_mabar_is_done_alter_mabar_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mabar',
            options={'ordering': ['date_created']},
        ),
    ]
