# Generated by Django 4.2.16 on 2024-09-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabar', '0005_alter_mabar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mabar',
            name='id_user',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='zone_user',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
