# Generated by Django 4.2.16 on 2024-09-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabar', '0006_alter_mabar_id_user_alter_mabar_zone_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mabar',
            name='id_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='zone_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
