# Generated by Django 4.2.16 on 2024-09-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabar', '0007_alter_mabar_id_user_alter_mabar_zone_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mabar',
            options={'ordering': ['date_created'], 'verbose_name': 'Mabar Record', 'verbose_name_plural': 'Mabar Records'},
        ),
        migrations.AlterField(
            model_name='mabar',
            name='catatan',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='donate_name',
            field=models.CharField(max_length=100, verbose_name='Nama Pendonasi'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='id_user',
            field=models.IntegerField(verbose_name='ID User'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Is Done'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='is_vvip',
            field=models.BooleanField(default=False, verbose_name='Is VVIP'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='jumlah_game',
            field=models.IntegerField(default=1, verbose_name='Jumlah Game'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='status',
            field=models.CharField(choices=[('antri', 'Dalam Antrian'), ('salah_id', 'Salah ID User'), ('kurang', 'Donasi Kurang')], default='antri', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='zone_user',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zone User'),
        ),
    ]
