# Generated by Django 4.2.16 on 2024-09-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabar', '0008_alter_mabar_options_alter_mabar_catatan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mabar',
            options={'ordering': ['-date_created'], 'verbose_name': 'Mabar Record', 'verbose_name_plural': 'Mabar Records'},
        ),
        migrations.AddField(
            model_name='mabar',
            name='telah_digunakan',
            field=models.IntegerField(default=0, verbose_name='Telah Digunakan'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='donate_name',
            field=models.CharField(max_length=100, verbose_name='Pendonasi'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='id_user',
            field=models.IntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='jumlah_game',
            field=models.IntegerField(default=1, verbose_name='Jumlah'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='status',
            field=models.CharField(choices=[('antri', 'Dalam Antrian'), ('in_mabar', 'Sedang Mabar'), ('prepare', 'Persiapan'), ('salah_id', 'Salah ID User'), ('kurang', 'Donasi Kurang'), ('done', 'Selesai')], default='antri', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='zone_user',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zone'),
        ),
    ]
