# Generated by Django 4.2.16 on 2024-09-16 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mabar', '0010_alter_mabar_catatan_alter_mabar_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusskin',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Tanggal Dibuat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonusskin',
            name='date_terkirim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Terkirim'),
        ),
    ]
