# Generated by Django 4.2.16 on 2024-09-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabar', '0011_bonusskin_date_created_bonusskin_date_terkirim'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_name', models.CharField(max_length=100, verbose_name='Pendonasi')),
                ('type_request', models.CharField(choices=[('meta', 'Hero Meta'), ('non_meta', 'Hero Non-Meta'), ('troll', 'Hero Troll'), ('lain', 'Lain-lain')], default='lain', max_length=10, verbose_name='Tipe Request')),
                ('hero_name', models.CharField(max_length=100, verbose_name='Nama Hero')),
                ('count', models.IntegerField(default=1, verbose_name='Jumlah Request')),
                ('catatan', models.TextField(blank=True, default='-', verbose_name='Catatan')),
                ('is_done', models.BooleanField(default=False, verbose_name='Sudah Selesai')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
            ],
            options={
                'verbose_name': 'Request Hero',
                'verbose_name_plural': 'Request Heroes',
                'ordering': ['-date_created'],
            },
        ),
    ]
