# Generated by Django 4.2.16 on 2024-09-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabar', '0014_alter_mabar_nickname_alter_mabar_zone_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mabar',
            name='catatan',
            field=models.TextField(blank=True, default='Pantau Status mabarmu!', null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='mabar',
            name='status',
            field=models.CharField(choices=[('antri', 'Antri Mabar'), ('antri_scrim', 'Antri Scrim'), ('salah_id', 'Salah ID User'), ('kurang', 'Donasi Kurang'), ('prepare', 'Persiapan'), ('in_mabar', 'Sedang Mabar'), ('done', 'Selesai')], default='antri', max_length=20, verbose_name='Status'),
        ),
    ]
