# Generated by Django 4.2.16 on 2024-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabar', '0015_alter_mabar_catatan_alter_mabar_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomenAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_name', models.CharField(max_length=100, verbose_name='Nama Pendonasi')),
                ('id_user_game', models.CharField(max_length=50, verbose_name='ID User Game')),
                ('zone_user_game', models.CharField(max_length=10, verbose_name='Zone User Game')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('is_done', models.BooleanField(default=False, verbose_name='Sudah Selesai')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Selesai Pada')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
            ],
            options={
                'verbose_name': 'Komen Album',
                'verbose_name_plural': 'Komen Albums',
                'ordering': ['-date_created'],
            },
        ),
    ]
